### ISSUE TITLE
Load all of swissprot

### ISSUE THREAD

**Issue by cmungall** [geneontology/neo#24] opened 2017-11-22 22:59 UTC
0.5m entries, we are already at 0.75m

**Comment by vanaukenk** [comment] 2020-11-18 01:58
This issue came up again at the GO-CAM Jamboree (2020-11-17).

GOA curators would like to be able to annotate to any SwissProt entry, e.g. a snake venom.

What do we (UniProt and GOC) need to do so this can happen?

**Comment by kltm** [comment] 2020-11-18 04:31
@vanaukenk At this point in time, we'd need a GAF or GPI file to load, then we'd add it into the NEO build process. I believe there was ongoing conversation about various possibilities with subset, or had we resolved that and we were going to do the while thing?

**Comment by kltm** [comment] 2022-03-18 21:04
I believe this is a dupe of #82

**Closed by kltm** 2022-03-18 21:04 UTC
Labels: enhancement, help wanted
