### ISSUE TITLE
Model made in graph editor  will not load into ART or Form 

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/neo#73] opened 2021-07-14 00:27 UTC
gomodel:5fce9b7300002524

We know there are several errors with incorrect PMID (PMID: 28581022 ) used for annotation to Il17a, Il17ra, Notch1, and Traf3ip2 that need to be corrected, which would be easier in ART, but it will not load. 
We can see gpad output from graphic view, but cannot get annotation preview
The annotations are coming into the MGI gpad and load into MGI

Is there something specific that is preventing loading into ART?

**Comment by vanaukenk** [comment] 2021-07-14 18:29
@kltm @tmushayahama @balhoff 

I'm not sure I understand what's going on with this particular model.  There looks to be annotation to protein-coding genes but it doesn't appear that MGI models containing annotations to protein-coding genes universally have this problem.

@tmushayahama  Can you confirm, for example, that the entities in gomodel:60e7989d00000247 do have associated root types?

@ukemi @hdrabkin

**Comment by ukemi** [comment] 2021-07-14 18:37
The model also looks a bit weird. It looks like some of the connections between generic MFs and BPs didn't save?

**Comment by ukemi** [comment] 2021-07-14 18:41
Do you want to use this for trouble-shooting or do you want me to go in and fix the refs? They are easy to find. What's the right PMID?

**Comment by ukemi** [comment] 2021-07-14 18:44
But now I can't even save the model. Seems like we have run into this before.

**Comment by vanaukenk** [comment] 2021-07-14 18:44
Ugh - is this the model we've had trouble saving in the past?

**Comment by ukemi** [comment] 2021-07-14 18:45
It might be. Looking at it, it almost looks like at some point it partially saved.

**Comment by vanaukenk** [comment] 2021-07-14 18:46
Hi - I just checked my notes from the various Noctua outages, and indeed, this is the model we've had trouble with in the past.

I know there are a lot of annotations there, but we may have to cut our losses and create a new model and mark this for deletion.

**Comment by ukemi** [comment] 2021-07-14 18:49
So this is really curious then because I looked at this model before and I didn't see all those 'anonymous' nodes.
If we create a new one, we should export the GPAD so we have a record of what's there and the annotations can be re-entered. Should we encourage splitting giant 'single annotation' models like this into smaller chunks?

**Comment by hdrabkin** [comment] 2021-07-14 18:55
We could at least change it to dev, so that it won't be output to our gpad; During the drop/reload, there will be no annotations using the offensive PMID to that it would now not have any data in MGI and could be deleted.

**Comment by hdrabkin** [comment] 2021-07-14 18:56
Dmitry will have the right PMID

**Comment by ukemi** [comment] 2021-07-14 18:58
I think we should have him export the GPAD from this model and then one of us should try to delete the model. Then we can use the GPAD to re-enter the data into a new model.

**Comment by ukemi** [comment] 2021-07-14 19:05
There are a couple strategies we could use. Let's discuss at lab meeting tomorrow.

**Comment by lpalbou** [comment] 2021-07-14 19:08
Seems like there are several issues here.

* GP not showing in ART. Most of them look valid and should show up in ART. Possible issues: 1) ART; 2) Discrepancies between the GOLr used to select a GP in Noctua graph and the one used to resolve a GP in ART; 3) if partially saved, this might have impacted the GP identifier and prevent the resolving of the root type / name of the gene

* Why this model is not saving. @kltm we would need the log for that to try to track down what's happening, if it's a memory issue, if it's a request just too big and crash the network or timeout, etc

**Comment by tmushayahama** [comment] 2021-07-14 19:21
@vanaukenk to reply https://github.com/geneontology/neo/issues/73#issuecomment-880116623 , no they don't have root types

**Comment by balhoff** [comment] 2021-07-14 19:42
This model still has that weird backquote in it. I would export the OWL from the UI, delete that character in a text editor,  manually commit this to github, and then reload models in Minerva. I don't think you need to lose anything.

**Comment by ukemi** [comment] 2021-07-14 19:43
I've exported the GPAD form this model and saved it on my machine. No matter what we do, the annotations will not be lost.
There are annotations to this gene:

MGI	MGI:2143599	involved_in	GO:0042493	PMID:19155511	ECO:0000315	MGI:MGI:3831153		20210121	MGI		noctua-model-id=gomodel:5fce9b7300002524|contributor=http://orcid.org/0000-0003-3394-9805|model-state=production
MGI	MGI:98283	involved_in	GO:0048255	PMID:21822258	ECO:0000314			20210128	MGI	has_participant(MGI:MGI:101835),has_participant(MGI:MGI:107548),has_participant(MGI:MGI:2143599),has_participant(MGI:MGI:98283)	noctua-model-id=gomodel:5fce9b7300002524|contributor=http://orcid.org/0000-0003-3394-9805|model-state=production
MGI	MGI:2143599	involved_in	GO:0042092	PMID:21856933	ECO:0000315	MGI:MGI:3510784		20210217	MGI	part_of(GO:0006954),has_participant(MGI:MGI:2155888),has_participant(CL:0000084),has_participant(CL:0000546)	noctua-model-id=gomodel:5fce9b7300002524|contributor=http://orcid.org/0000-0003-3394-9805|model-state=production

**Comment by kltm** [comment] 2021-07-14 20:01
Okay, this seems like a dupe of  https://github.com/geneontology/minerva/issues/379

**Comment by balhoff** [comment] 2021-07-14 20:02
@kltm should you and I coordinate on a Minerva reload and restart time to take care of this?

**Comment by kltm** [comment] 2021-07-14 20:04
@balhoff I'm making notes on the other ticket

**Comment by deustp01** [comment] 2021-07-14 20:04
> that weird backquote in it

Question from left field - is this the sort of problem that could arise if a curator tried to copy-paste text straight from a Word document with all its wonderful non-ASCII quote characters, into a Noctua form? So a long-term fix is still more curator training, emphasizing the need for plain text?

**Closed by kltm** 2021-07-14 20:04 UTC
Labels: bug

**Comment by kltm** [comment] 2021-07-14 20:11
@deustp01 Could be, although in this case, it may be from the more permissive graph editor
 Long term, fixes will be a combination of:

* curator training
* smarter client inputs that prevent bad things from getting in
* smarter server checking that prevents bad things from getting saved

https://github.com/geneontology/minerva/issues/379 was originally formulated with a bit of the last one in mind.

**Comment by tmushayahama** [comment] 2021-07-14 23:31
> > that weird backquote in it
> 
> Question from left field - is this the sort of problem that could arise if a curator tried to copy-paste text straight from a Word document with all its wonderful non-ASCII quote characters, into a Noctua form? So a long-term fix is still more curator training, emphasizing the need for plain text?

I don't think it's possible because the value entered in Noctua Form is the resolved ids not the  copied text as we are using autocomplete. I think it is an upstream problem. Lemme double check
