### ISSUE TITLE
Request to load more phage proteins

### ISSUE THREAD

**Issue by dsiegele** [geneontology/neo#95] opened 2022-05-03 22:17 UTC
I tried to build some models for pathways in phage, but discovered that very few of the reviewed UniProt IDs were loaded.
There were a few proteins available for QBeta and MS2, but none for:
- Bacteriophage Lambda (Taxon 10710; 88 reviewed proteins)
- Bacteriophage T4 (Taxon 10665; 268 reviewed proteins)
- Bacteriophage T7 (Taxon 10760; 57 reviewed proteins)
- Bacteriophage P1 (Taxon 10678; 33 reviewed proteins)
- Bacteriophage N4 (Taxon 10752; 7 reviewed proteins)

Also, there are only a small number of reviewed proteins for some phages. Is it possible to request for these phages that unreviewed proteins be loaded?

**Comment by kltm** [comment] 2022-05-04 00:28
Dupe of https://github.com/geneontology/neo/issues/94

**Closed by kltm** 2022-05-04 00:28 UTC
